# Runs all tests and runs a coverage report via python-coverage-comment-action.
name: Coverage

on:  # Runs on all push events to main branch and any push related to a pull request
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:  # Allow manual triggering

env:
  UV_COMPILE_BYTECODE: 1

defaults:
  run:
    shell: bash

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      # Gives the action the necessary permissions for pushing data to the
      # python-coverage-comment-action branch, and for editing existing
      # comments (to avoid publishing multiple comments in the same PR)
      contents: write
    env:
        python-version: "3.13"

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: true

      - name: Install uv and Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ env.python-version }}
          enable-cache: true
          activate-environment: true
          cache-dependency-glob: 'pyproject.toml'

      - name: Ensure pip, setuptools and wheel
        run: uv pip install --upgrade pip setuptools wheel

      # The uv pip should make & use an env from the Python install of the previous step
      - name: Install package
        run: uv pip install '.[test,tracking]'

      - name: Install dependencies from GitHub
        run: uv pip install git+https://github.com/jgray-19/xtrack_tools.git git+https://github.com/jgray-19/tmom-recon.git git+https://github.com/jgray-19/pymadng-utils.git

      # - name: Prebuild xsuite kernels
      #   run: xsuite-prebuild r

      - name: Run all tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          python -m pytest tests/ --cov=aba_optimiser

      - name: Coverage comment
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}